#!/bin/sh

PGPASSWORD=${APP_POSTGRESQL_DB_PASSWORD} psql -h "${APP_POSTGRESQL_DB_HOSTNAME}" -U "${APP_POSTGRESQL_DB_USERNAME}" "${APP_POSTGRESQL_DB_NAME}" -c "CREATE TABLE IF NOT EXISTS USERS(NAME CHAR(50));"
